### ISSUE TITLE
DER Aggregation MW for Commercial and Industrial when dera_aggregation_perc is 0

### ISSUE THREAD

**Issue by elainethale** [nrel-hem/HolisticElectricityModel.jl#29]
E.g., for WM, FlatRate, IncentiveCurve1, have

Year,Zone,aggregation_perc
2021,p129,0.0
2021,p130,0.0
2021,p131,0.0
2021,p132,0.0
2021,p133,0.0
2021,p134,0.0
2022,p129,0.0
2022,p130,0.0
2022,p131,0.0
2022,p132,0.0
2022,p133,0.0
2022,p134,0.0

But

Year,Zone,CustomerType,aggregation_stor_mw
2021,p129,Commercial,0.011686511450004667
2021,p129,Industrial,0.011686511450004667
2021,p129,Residential,0.08420691782249844
2021,p130,Commercial,0.011785305515462384
2021,p130,Industrial,0.011785305515462384
2021,p130,Residential,0.08491877642863065
2021,p131,Commercial,0.022301330781514975
2021,p131,Industrial,0.022301330781514975
2021,p131,Residential,0.06690399234454492
2021,p132,Commercial,0.012289335637505667
2021,p132,Industrial,0.012289335637505667
2021,p132,Residential,0.0885505551034332
2021,p133,Commercial,0.012511648897564648
2021,p133,Industrial,0.012511648897564648
2021,p133,Residential,0.09015242872506309
2021,p134,Commercial,0.011668764293888372
2021,p134,Industrial,0.011668764293888372
2021,p134,Residential,0.08407904105422065

**Comment by Nongchao** [comment]
Can you point me to the HEM branch you're using and the associated data on HPC? It *might be a quick fix.

**Comment by elainethale** [comment]
I'm assuming that #30 fixes this and will confirm in the next set of runs.
